### ISSUE TITLE
Renew the appearance of the application

### ISSUE THREAD

**Issue by wuniversales** [zoff99/ToxAndroidRefImpl#122]
Hello, I think it is necessary to renew the appearance of the application, the current appearance needs some tweaking.

For example, in chat, it would be a good idea to remove the upper "chat" bar, it is useless, just to take up space on the screen.

![Screenshot_20200121-123720](https://user-images.githubusercontent.com/48658161/72802188-2174ce80-3c43-11ea-93e3-f5d525551296.png)

As for the main screen.
The circle to add friends should be removed, and offer the option in the side menu, below the user profile, 
The image of the trifa I would remove, it is ugly in my opinion.

![Screenshot_20200121-123757](https://user-images.githubusercontent.com/48658161/72802541-efb03780-3c43-11ea-9b18-f641e56803d1.png)

Silence the conversation should not appear in that area, it should appear within the profile of each user.

Regards

**Comment by migulen** [comment]
First of all... sorry for my poor english.

"Hello, I think it is necessary to renew the appearance of the application, the current appearance needs some tweaking." **I think the same.**

"For example, in chat, it would be a good idea to remove the upper "chat" bar, it is useless, just to take up space on the screen." **Totally true**

"As for the main screen.
The circle to add friends should be removed, and offer the option in the side menu, below the user profile," **I think the circle add it's ok, it's a common use shortcut, but must go in the upper bar, where "TRiFa" is located.**

"The image of the trifa I would remove, it is ugly in my opinion." **It's not about ugly or not... it's not necessary for functionality. It's nice to have an app "as clear as possible".** 

"Silence the conversation should not appear in that area, it should appear within the profile of each user." **Uhmm... the bell is a very usefull shortcut... in my opinion it's nice in this position.**

Just this, for now.

**Comment by riveravaldez** [comment]
I add: emoticons and speech bubbles are too big and take too much space of screen, making conversation harder to follow.
And, FWIW, I think the TRIfA app is great. :)

**Comment by ghost** [comment]
How about using the GUI of other projects?

GPLv3+ licensed (+ means "or any later version"):
Signal https://github.com/signalapp/Signal-Android/blob/master/LICENSE (not sure if this also allow "any later version")
Kontalk https://github.com/kontalk/androidclient/blob/master/COPYING
GNU Jami https://git.jami.net/savoirfairelinux/ring-client-android/blob/master/COPYING
Conversations: https://github.com/iNPUTmice/Conversations/blob/master/LICENSE

permissive licenses (wouldn't require using GPLv3 for the combined work, since TRIFA uses GPLv2 (although GPLv3 is the recommended one by the Free Software Foundation and GNU Project anyway)):
RiotX (Apache v2) https://github.com/vector-im/riotX-android/blob/develop/LICENSE
Rocket.Chat (MIT) https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/LICENSE -- Uses React Native so can be used for other platforms as well.

See for example Google Play Store to see how each app's GUI looks.

I'm interested in more alternatives with interfaces you like if you know any. Cheers!
