### ISSUE TITLE
own Avatar can not be saved sometimes

### ISSUE THREAD

**Issue by zoff99** [zoff99/ToxAndroidRefImpl#47]
own Avatar can not be saved sometimes

**Comment by ahyar92** [comment]
Hi @zoff99, I encountered an error while uploading a profile  photo in TRIfA

## The app does not respond when changing profile photos with slightly larger sizes
#### Expected behavior
Supposedly, I can change the profile with a larger size image.

#### Actual behavior
When I change the profile picture and select an image with size above 4MB, the application suddenly crashes and does not respond, and the app goes out by itself.

#### How to reproduce
1. Install and open the app
2. Next, open the profile menu
3. Change the profile picture by clicking on the avatar icon
4. Select an image with a file size above 4MB, then the application will crash and not respond


- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 1.0.16 

#### Recording Of The Bug
https://www.youtube.com/watch?v=KMqWmboxan0

**Comment by zoff99** [comment]
duplicate of #62
