### ISSUE TITLE
Feature Request: Audio Chat Only

### ISSUE THREAD

**Issue by krasjev** [zoff99/ToxAndroidRefImpl#66]
It would be great if one could make audio calls only:

1. To start a an audio call (instead of a video call)
2. To toggle video on and off during a call

**Comment by hkarel** [comment]
@zoff99, I ask you to pay attention to this proposal. I have two reasons for this:

1. At this time, it is impossible make calls to my client (ToxPhone), since my client supports only audio calls;
2. At the weak internet-channel transfer of video will hammer all bandwidth.Communication will be either very bad, or even impossible. The audio will have at least a chance.

**Comment by Klagio** [comment]
> @zoff99, I ask you to pay attention to this proposal. I have two reasons for this:
> 
> 1. At this time, it is impossible make calls to my client (ToxPhone), since my client supports only audio calls;
> 2. At the weak internet-channel transfer of video will hammer all bandwidth.Communication will be either very bad, or even impossible. The audio will have at least a chance.

3. Many are interested only in audio calls, no video

**Comment by zoff99** [comment]
@hkarel you can make an audio call with TRIfA when you hold the phone to your ear. the sensor will then disable video.
if we had only 1% of the people demanding changes really helping out then things could be done.
without any help, things will stay the same.

**Comment by Klagio** [comment]
> the sensor will then disable video

on my phone the camera stays on. The other user will see inside my ear  :)

**Comment by zoff99** [comment]
PR's welcome.

**Comment by zoff99** [comment]
was mostly implemented already
