### ISSUE TITLE
compile error,  'stdio.h' file not found

### ISSUE THREAD

**Issue by Jefferson-111** [zoff99/ToxAndroidRefImpl#69]
#### 
Android OS Version: android 8.0
code branch: zoff99/dev003
Description: I didn't run this project on my Android Studion, and error info is:
/my_codes/ToxAndroidRefImpl/android-refimpl-app/library/src/main/jni/include/speex/coffeecatch.c
Error:(44, 10) fatal error: 'stdio.h' file not found
Warning:warning: -Wl,--no-merge-exidx-entries: 'linker' input unused [-Wunused-command-line-argument]
/Users/wangxuefang/my_codes/ToxAndroidRefImpl/android-refimpl-app/library/src/main/jni/libspeexdsp/os_support.h
Error:(37, 10) fatal error: 'string.h' file not found

#### Screenshots (if possible):
![image](https://user-images.githubusercontent.com/3921773/40884396-7883627e-6745-11e8-91ca-3f996d4cdccd.png)

Hope you can help me to solve this problem

**Comment by vynmera** [comment]
I'm having the same issue on Windows.

**Comment by zoff99** [comment]
what does this mean:
```I didn't run this project on my Android Studion```
if you do not compile it as documented i can not really help

**Comment by zoff99** [comment]
to compile use the official Android Studio and follow these steps exactly:
https://github.com/zoff99/ToxAndroidRefImpl#compile-in-android-studio

**Comment by vynmera** [comment]
@zoff99 I'm not sure about OP, but I followed those instructions with no luck.

**Comment by zoff99** [comment]
@vynmera did you install NDK and Cmake in android studio?

**Comment by vynmera** [comment]
@zoff99 Yep, those are installed.

**Comment by zoff99** [comment]
@vynmera can you upload a screenshot of your exact errors please.

**Comment by askymore** [comment]
@wangxuefang  @vynmera I have the same issue on Windows.To solve this problem,you should not use the latest version of NDK.You can download r13b or r15b ,and change NDK location in the project structure

![image](https://user-images.githubusercontent.com/23046392/41265454-ed2b35c6-6e24-11e8-8aa7-f8e86fe486ca.png)

**Comment by zoff99** [comment]
@askymore can you provide full screenshots for all steps please?
so we can add it to the README.md

**Comment by askymore** [comment]
This issue seems to  caused by the AS3.0 and the latest version of NDK, nothing to do with Windows or Linux.To solve this problem,you should  download NDK version r13b( http://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip  )  Unzip the file to somewhere like '\home\kevin\android-ndk', and then change NDK location in the project structure

the menu path is File->Project Structure

![image](https://user-images.githubusercontent.com/23046392/41277904-14847cfa-6e5b-11e8-962d-f2a3b79bdb0c.png)

change the default Android NDK Location to the old version of NDK , and it works!
![image](https://user-images.githubusercontent.com/23046392/41278140-aaf86750-6e5b-11e8-8344-a64dfcf5b6a8.png)
